# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-30 19:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('descriptions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Icon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to=b'gfx/icons/')),
            ],
        ),
        migrations.CreateModel(
            name='POI',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('modification_date', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('lat', models.DecimalField(decimal_places=9, max_digits=13)),
                ('long', models.DecimalField(decimal_places=9, max_digits=13)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('description', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='descriptions.Description')),
                ('event', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='descriptions.Event')),
                ('icon', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='map.Icon')),
                ('main_faction', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='poi_main_faction', to='descriptions.Faction')),
                ('modification_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('place', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='descriptions.Place')),
                ('related_factions', models.ManyToManyField(blank=True, to='descriptions.Faction')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Polygons',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('modification_date', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('polygon', models.TextField()),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('description', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='descriptions.Description')),
                ('event', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='descriptions.Event')),
                ('main_faction', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='poly_main_faction', to='descriptions.Faction')),
                ('modification_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('place', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='descriptions.Place')),
                ('related_factions', models.ManyToManyField(blank=True, to='descriptions.Faction')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
